### ISSUE TITLE
Reduce to 5 public factory functions: `manifest`,  `session`, `channel`, `unit`, `probe`

### ISSUE THREAD

**Issue by DylanMuir** [emeyers/Brain-Observatory-Toolbox#33]
Streamline API by making some classes non-public-facing

- [x] manifest
- [x] session
- [x] probe
- [x] channel
- [x] unit
- [x] make other interfaces private

**Comment by DylanMuir** [comment]
Implemented in c07b83dfd20c4d65de8bc368671d86760735521c

**Comment by DylanMuir** [comment]
@vijayiyer05 Please review

**Comment by DylanMuir** [comment]
@vijayiyer05 Flagging an issue: The factory functions for `channel`, `unit`, etc. all require access to the manifest — which then needs to be loaded from disk. This implies that the new syntax:
`
c1 = bot.channel(...)
c2 = bot.channel(...)
`

is slower than

```
m = bot.manifest('ephys')
c1 = m.channel(...)
c2 = m.channel(...)
```

**Comment by vijayiyer05** [comment]
@DylanMuir  I think somewhere in my back-of-a-napkin notes I wondered if the `manifest `object could be retired. It sounds to me like it's important that it remains. It seems like it could be a `bot.internal.*` class and should follow the singleton pattern. Then the factory function implementations could access it as needed and avoid unnecessarily repeated construction.

**Comment by DylanMuir** [comment]
Ok, adopting a singleton pattern improves performance considerably. We can easily create new factory functions for `fetchSessions`, `fetchUnits`, etc. as necessary.

**Comment by vijayiyer05** [comment]
Glad to hear this! I looked at `iss36` and that seems the right idea/direction to me. Seems all clear to go forth. 

Aside: I might have said "unnecesarily repeated _active_ construction". In this case, my personal stylistic preference is to use the constructor call to retrieve the singleton instance, actively constructing it the first time, and so the static method `instance()` would be internal to the class rather than a factory function. But this is all in developer-land and no need to change.
