### ISSUE TITLE
“Stylistic unification” for all exposed functions & classes

### ISSUE THREAD

**Issue by DylanMuir** [emeyers/Brain-Observatory-Toolbox#36]
- [x] Remove redundancies in naming, e.g. the `BOT_Session_Type` property in the `bot.session` package can be simply `Type`
- [x] Remove type prefixes from all exposed property & variable names, e.g. `tOphysSessions` would become `Sessions` (also removing redundancy)
- [x] Replace `get_XXX()` methods for accessing property values with MATLAB property access methods having the form `get.XXX()`

**Comment by DylanMuir** [comment]
@vijayiyer05 Regarding replacing `get_XXX()` methods with MATLAB property getters, I'm slightly concerned. The reason we didn't do this at the beginning, is that most of those `get_XXX()` methods are heavy (requiring large data loading from disk, or downloading).

* If we convert them into visible MATLAB properties, then any time you display the object, data will be loaded — making the object not "lightweight" anymore. Having lightweight objects is a good design goal in my opinion, since the metadata can be accessed and manipulated without downloading the NWB file.
* If we make them hidden MATLAB properties, then I think we have a "discoverability" issue. You can't see how to access and manipulate the data by looking at the list of properties and methods. Autodoc doesn't help here, I think, since hidden properties  won't be included
* Finally, some of the `get_XXX()` methods actually accept arguments (mimicking the Allen Brain API), which is not possible for getter methods.

Please let me know what you prefer.

**Comment by vijayiyer05** [comment]
Thanks @DylanMuir for capturing some of these earlier considerations leading to the use of ordinary methods rather than property access methods. 

My current thinking would be generally to use visible MATLAB properties and to employ the [custom display interface](https://www.mathworks.com/help/matlab/matlab_oop/custom-display-interface.html) API to prevent automatic loading upon object display. The "footer" would have a link to access more properties, and could include also a brief note indicating this would trigger a download. This way folks would think twice before clicking the link. To see an example of the custom display interface in action, can simply look at the display for a plain figure object handle: `>> hFig = figure`

For the current `get_XXX()` methods accepting arguments, then I would keep these as ordinary methods, but would rename them to something that doesn't start with `get`.

**Comment by vijayiyer05** [comment]
Hi @DylanMuir, I took a look through the `iss36`  branch. Great to see the plumbing is working out (singleton, custom display, etc) towards the overall API direction. 

For `ophyssession`, I'm noticing that some of the `get_XXX() `methods without arguments (besides the object reference) remain as methods rather than being converted to properties, e.g. `get_spontaneous_activity_stimulus_table` and most of the `get_XXX()` methods thereafter.

I'm wondering if these correspond to even longer computations that seem better to leave out of the lazy display?

**Comment by DylanMuir** [comment]
@vijayiyer05 These remaining `get_` methods are all resolved in #37 for the public-facing classes. If you review and merge #43 then review and merge #37, all will be well!
