### ISSUE TITLE
Refactor public API

### ISSUE THREAD

**Issue by DylanMuir** [emeyers/Brain-Observatory-Toolbox#46]
Generally speaking, the tables seem effectively like workspace variables, not really used by their current classes. So the thinking is for the public API (the root bot package) to include the following functions each of which returns a table object:
`fetchSessions` [with an arg identifying whether to fetch the ophys or ephys sessions]
`fetchExperiments` [with an arg identifying whether to fetch the ophys or ephys experiments]
`fetchChannels`
`fetchProbes`
`fetchUnits`
The internal implementations (e.g. for caching matters) could live in bot.internal and I’m guessing that’s where ephyssessions & ophyssessions could live if needed, and need not be exposed to the user API the way I’m currently imagining.  The user could create their own variable names to differentiate separate ophys & ephys variables where the possibility for both exists.
 
Besides these fetch functions, I’m imagining the public API would contain the following user-facing classes:
`session`
`experiment`
`channel`
`probe`
`unit`

- [x] Implement `experiment` class for OPhys experiment containers
- [x] Implement `fetchXXX` functions
- [x] Move manifest classes to `bot.internal`

**Comment by DylanMuir** [comment]
@vijayiyer05 Implemented in ff458e7dc9f6f96254ed108ca833ee0eaa1ed3f1

**Comment by DylanMuir** [comment]
Closed out by #47

**Comment by vijayiyer05** [comment]
@DylanMuir Reopening because there currently isn't a public `experiment` factory function (as of cd750366f), i.e. to construct the `bot.internal.experiment ` class. That seems to be the one missing element to round out the public API. I believe it could be of the trivial pattern as with `probe`, `session`, & `unit`.  If so, please assign to me to implement. If you see any reasons/considerations that a more complex implementation is needed, please comment.

**Comment by vijayiyer05** [comment]
@DylanMuir Reopening because there currently isn't a public `experiment` factory function (as of cd750366f), i.e. to construct the `bot.internal.experiment ` class. That seems to be the one missing element to round out the public API. I believe it could be of the trivial pattern as with `probe`, `session`, & `unit`.  If so, please assign to me to implement. If you see any reasons/considerations that a more complex implementation is needed, please comment.

**Comment by DylanMuir** [comment]
@vijayiyer05 Added in a836f588e3abeba3bb84901efb05ad9cfb026c09 along with a unit test

**Comment by vijayiyer05** [comment]
@DylanMuir 
My bad for accidental re-open. 

Just wanted to leave a comment to bounce an idea:  move the "item" classes to a new `bot.item.*` package, so they're separated from the more inner-ring 'bot.internal.*' contents. These item classes would this way be "semi-public" and would be the classes explicitly linked to the factory functions in the root folder.
